"""empty message

Revision ID: a475696cd0c6
Revises: dcfdbc640414
Create Date: 2022-02-12 00:33:37.904627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a475696cd0c6'
down_revision = 'dcfdbc640414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpokedata',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('pokedataid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokedataid'], ['pokedata.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userid', 'pokedataid')
    )
    op.drop_table('user_pokedata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pokedata',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pokedata_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pokedata_id'], ['pokedata.id'], name='user_pokedata_pokedata_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_pokedata_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'pokedata_id', name='user_pokedata_pkey')
    )
    op.drop_table('userpokedata')
    # ### end Alembic commands ###
